services:
  db-jenkins:
    image: postgres:15
    container_name: blog-db-v2-jenkins
    environment:
      POSTGRES_USER: blogadmin
      POSTGRES_PASSWORD: BlogPass123!
      POSTGRES_DB: blogdb
    volumes:
      - postgres_data_jenkins:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app-jenkins:
    image: mumtaz02/mydailyblog-app:latest
    container_name: blog-app-v2-jenkins
    depends_on:
      - db-jenkins
    environment:
      DATABASE_URL: postgresql://blogadmin:BlogPass123!@db-jenkins:5432/blogdb
      NEXTAUTH_SECRET: mysupersecretkey123456789
      NEXTAUTH_URL: http://13.206.144.86:3001  
      AUTH_SECRET: mysupersecretkey123456789
      AUTH_URL: http://13.206.144.86:3001     
      AUTH_TRUST_HOST: "true"
      PORT: 3000
      NODE_OPTIONS: "--experimental-global-webcrypto"
    ports:
      - "3001:3000"

volumes:
  postgres_data_jenkins: